### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by bojtalepenye** [sanidhyy/duolingo-clone#20]
**Is your feature request related to a problem? Please describe.**
I'd like to set this project up in a docker contianer. 

**Describe the solution you'd like**
I am no web developer and that's why I am asking the creator here, if he could add a Dockerfile and gave us instructions on how to set the application up in a simple docker image and then run it in a container.

**Comment by sanidhyy** [comment]
Hi @bojtalepenye, I recommend checking out this beginner-friendly [Medium article](https://medium.com/@itsuki.enjoy/dockerize-a-next-js-app-4b03021e084d) that provides a step-by-step guide on how to dockerize a Next.js app. It should help you get started with setting up the project in a Docker container.
