### ISSUE TITLE
Database string cannot connect

### ISSUE THREAD

**Issue by bryan1101023** [sanidhyy/duolingo-clone#25]
So, in vercel it shows this message even though the database url is correct? 
<img width="649" alt="image" src="https://github.com/user-attachments/assets/4ce417f0-de73-4102-8862-2cebc88f3294" />

**Comment by bryan1101023** [comment]
Solved this but now it says this:
<img width="1092" alt="image" src="https://github.com/user-attachments/assets/52de0c7c-da61-40ef-a9d5-25124a0990dc" />

**Comment by sanidhyy** [comment]
Could you check the logs in your Vercel dashboard to see if they provide any insights? @bryan1101023

**Comment by sanidhyy** [comment]
This issue has been closed since it didn't received any activity in a while.
