### ISSUE TITLE
npm run db:prod not working due to relation does not exist

### ISSUE THREAD

**Issue by popcake456** [sanidhyy/duolingo-clone#8]
**Describe the bug**
no issue until part 11 , after running npm install --legacy-peer-deps ,i got a msg ,2 high severity vulnerabilities ,after that i tried to run,npm run db:prod , and got the msg of relation "user_progress ,etch" 

**To Reproduce**
1. finish the 10 steps on getting started
2. run npm install --legacy-peer-deps , today as for sept 12 2024
3. on terminal run npm run db:prod 
4. thats the error

**Expected behavior**
[localhost](http://localhost:3000/learn) will not load and same error will occur

**Screenshots**
![image](https://github.com/user-attachments/assets/f9a381a8-737e-4d8d-84b0-98ab2d6c7ed3)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser opera gx

**Additional context**
im guessing it  hast to do with drizzle/db

**Comment by sanidhyy** [comment]
Hi @popcake456 Thanks for pointing it out. You need to run `npm run db:push` before running prod script. I have updated readme instructions as well.
